{% set version = "0.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-param6
  version: {{ version|replace("-", "_") }}

source:
  url: https://raphaels1.r-universe.dev/src/contrib/param6_{{ version }}.tar.gz
  sha256: 998e61c7ed70a74ed7e7590f3ad9561f

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-data.table
    - r-dictionar6 >=0.1.2
    - r-r6
    - r-set6 >=0.2.3
  run:
    - r-base
    - r-checkmate
    - r-data.table
    - r-dictionar6 >=0.1.2
    - r-r6
    - r-set6 >=0.2.3

test:
  commands:
    - $R -e "library('param6')"           # [not win]
    - "\"%R%\" -e \"library('param6')\""  # [win]

about:
  home: https://xoopR.github.io/param6/
  dev_url: https://github.com/xoopR/param6/
  license: MIT
  summary: By making use of 'set6', alongside the S3 and R6 paradigms, this package provides a fast and lightweight R6 interface for parameters and parameter sets.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
